version: '3'

services:
  svc-brookclient-nginx:
    image: nginx:1.23
    container_name: brookclient-nginx
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PKG_RELEASE=1~bullseye
      - NGINX_VERSION=1.23.3
      - NJS_VERSION=0.7.9
    ports:
      - "49800:80"
      - "49801:443"
      - "49802:8080"
    volumes:
    - /share/VMs/plugindata/brookclient/dist:/usr/share/nginx/html
    - /share/VMs/plugindata/brookclient/nginx/conf.d:/etc/nginx/conf.d

  svc-brookclient-flask:
    image: brookclient:v1
    container_name: brookclient-flask
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    environment:
      - TOGOOGLE_WHO=brook
      - TOGOOGLE_SERVERIP=
      - TOGOOGLE_SERVERPORT=
      - TOGOOGLE_PASSWORD=
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt
    ports:
      - "49803:1080"
      - "49804:80"
      - "49805:8080"
    volumes:
    - /share/VMs/plugindata/brookclient/livepatch:/livepatch
    - /share/VMs/plugindata/brookclient/config/v2ray_config.json:/opt/v2ray/config.json
    - /share/VMs/plugindata/brookclient/program/togoogle.sh:/opt/togoogle.sh
    # - /share/VMs/plugindata/brookclient/program/brook:/opt/brook
    # - /share/VMs/plugindata/brookclient/program/v2ray:/opt/v2ray